name       : kldap
version    : 21.08.1
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kldap-21.08.1.tar.xz : 8f04badfb568f529e79b10040b8c0203c8c80bca80ff6caeea6dfc5c4d9b22d5
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
