name       : kldap
version    : 22.08.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kldap-22.08.3.tar.xz : 74d0b24f4c1d93ab8c7c149242c54ea5322468ba29f2bdb8845d2fd96bba4d9a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
