name       : kldap
version    : 23.04.3
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kldap-23.04.3.tar.xz : 1546245e58ad67c04e2c91cef52129199477aa7a1f7f6381eb21413e0590e542
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
