name       : kldap
version    : 18.12.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kldap-18.12.2.tar.xz : de6f23e2bb6ac189856c0695b9468a914d486b5e2f47400562f250abcdd7e7f4
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
