name       : kldap
version    : 20.12.3
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kldap-20.12.3.tar.xz : 4c0cbcdffe92b0f7884721f564702aab65a208e5938c9a118a1ef30082d9d653
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - kwallet-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
