name       : kldap
version    : 21.08.2
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kldap-21.08.2.tar.xz : 7c7f241675dd768e20f8cd50f74a7c40658efc555af899ee128204cc932589ed
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
