name       : kldap
version    : 22.04.1
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kldap-22.04.1.tar.xz : 0bd291d6b2695e97813c00203c94a0d76f19d0898ab7ab70f0a7c59a10d806dc
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
