name       : kldap
version    : 21.12.1
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kldap-21.12.1.tar.xz : 7d61b4d4dc31870054e984ec34304fbd2f804f63125c4b2df04003f48aa60c8a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
