name       : kldap
version    : 18.04.3
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kldap-18.04.3.tar.xz : 5bdc40598087b1502317cd4458fe18489deca1f9296aa91718ae841da88a5cee
license    : LGPL-2.1
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
