name       : kldap
version    : 17.08.2
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kldap-17.08.2.tar.xz : ec2e2f148628ed1633b138af4019ace65bd108f15ff9c8aa238ba128616e1edc
license    : LGPL-2.1
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API.
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
