name       : kldap
version    : 22.04.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kldap-22.04.2.tar.xz : 60d934c1a2468ed2012033d9953652a7524e68d36820a8f31de884e13c343a83
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
