name       : kldap
version    : 18.08.2
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kldap-18.08.2.tar.xz : 55a4a4b41d503ffd53f13b7cdda94897853f37e2b6a4c5adaf780dbf21e96c89
license    : LGPL-2.1
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
