name       : kldap
version    : 22.04.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kldap-22.04.0.tar.xz : 317853dc9a7291c4325336fbfef3003c955de93db00107c11b5f27e6f3acd3fc
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
