name       : kldap
version    : 21.12.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kldap-21.12.3.tar.xz : 0abce0ebca12a6ee71e6b93a727579d20900fdbc750f059283dbd1d4a1d3948e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
