name       : kldap
version    : 20.12.2
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kldap-20.12.2.tar.xz : cbd06f4f2adfb2f0e539e36572eda31af582c4c62519f714ce0ffc8757d74fda
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - kwallet-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
