name       : kldap
version    : 21.08.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kldap-21.08.3.tar.xz : a1318c5f4b725b3212bae7caa3249d0896c30710ff1466d85755b3787b9961c9
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
