name       : kldap
version    : 18.04.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kldap-18.04.2.tar.xz : fa0b48d50c2581dafcfb3518c6731a7a2b8ff9878938bcfeaf432fe00dc898ca
license    : LGPL-2.1
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
