name       : kldap
version    : 17.04.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kldap-17.04.1.tar.xz : 5a54778faf4d9061e0ff9f220a47eced46a83071793eae34a6bac5537e5fb68d
license    : LGPL-2.1
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API.
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
