name       : kldap
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kldap-18.04.0.tar.xz : a976031e7f2358e94d5f7a0fc7ce9adfc3dcd3d52b045ba627d456ab6d3450ba
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Allows LDAP accessing with a convenient Qt style C++ API.
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
