name       : kldap
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kldap-17.08.3.tar.xz : 5bfffb36c6dd1a53b87a3d4d81e67f5f117d9ac4fa498eeff4fa5e44982bdd2e
license    : LGPL-2.1
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API.
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kmbox-devel
    - kmime-devel
    - kwidgetsaddons-devel
    - openldap-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
