name       : kldap
version    : 22.04.3
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kldap-22.04.3.tar.xz : e55cdf712f80e151d7f91feeba74697668e42e3ad1002dcdffc896ef9c7c9d08
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
