name       : kldap
version    : 21.04.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kldap-21.04.2.tar.xz : 447efa62357909659d085d93e8b2aa52f893ac4873c67769b8512a58ce1bb5b9
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
