name       : kldap
version    : 21.12.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kldap-21.12.0.tar.xz : 6f78eadf6e0bc7a6c4bb0ddea699393f5506f093163cc803194d75024d3ed760
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
