name       : kldap
version    : 23.04.2
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kldap-23.04.2.tar.xz : cccf41aa9a8e80944bb72e7baa271b81a84777ed672e662e0279582ea7e0c342
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
