name       : kldap
version    : 20.08.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kldap-20.08.1.tar.xz : 098fb07b280ef25dcf04b18f627223014257f6c0874b2959f2a8e68cacdb74a7
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwallet-devel
    - kwindowsystem-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
