name       : kldap
version    : 19.08.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kldap-19.08.3.tar.xz : b65ba5fefab7ecb92a7d38ac718e53077d9d9a87d73f121e32019aad90b48bae
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
