name       : kldap
version    : 23.04.1
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kldap-23.04.1.tar.xz : 008862023f998eda519ce359629e17ca5f75a851f5c60f207a35adf0d3ab64ce
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
