name       : kldap
version    : 21.04.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kldap-21.04.3.tar.xz : 7a8e8ba7ab4795eaab82736170ac1792d79675c702ad43ff088f97577988c238
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(libsasl2)
    - kdoctools-devel
    - kio-devel
    - openldap-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
